[platformio]
default_envs = selector

[env:selector]
platform = platformio/espressif32@5.4.0
platform_packages =
    platformio/framework-espidf@3.40407.240606
    espressif/toolchain-xtensa-esp32s3@8.4.0+2021r2-patch5
    espressif/toolchain-riscv32-esp@8.4.0+2021r2-patch5
    platformio/toolchain-esp32ulp@1.23500.220830
    platformio/tool-cmake@3.16.4
    platformio/tool-ninja@1.7.1
    platformio/tool-esptoolpy@1.40400.0
    platformio/tool-scons@4.40801.0
framework = espidf
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.flash_mode = dio
board_build.partitions = partitions.csv
monitor_speed = 115200
