import copy
import hashlib
import struct
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts" / "device"))
from layout import (
    MANIFEST_SCHEMA,
    SECTOR,
    STORAGE_EPOCH,
    app_record,
    board_file,
    boards,
    flash_size,
    flash_size_code,
    installed_version,
    layout_header,
    partition,
    partition_binary,
    partitions,
    record_offset,
    settings_erase_required,
    sha,
    validate_image,
    validate_manifest,
    version_key,
)

V4 = "heltec-v4-oled"
V3 = "heltec-v3"
MESHCORE_VERSIONS = ["companion-v1.17.1", "companion-v1.16.0"]


def image_fixture(board_id=V4):
    header = bytearray(24)
    header[0:4] = bytes([0xE9, 1, 2, flash_size_code(flash_size(board_id)) << 4 | 0xF])
    struct.pack_into("<H", header, 12, 9)
    header[23] = 1
    payload = struct.pack("<I", 0xABCD5432) + bytes(252)
    image = header + struct.pack("<II", 0x3C000020, len(payload)) + payload
    checksum = 0xEF
    for byte in payload:
        checksum ^= byte
    image += bytes(15) + bytes([checksum])
    return bytes(image + hashlib.sha256(image).digest())


def image_entry(board_id, name, offset, size=336, digest="a" * 64):
    return dict(file=board_file(board_id, name), offset=offset, size=size, sha256=digest)


def board_fixture(board_id):
    def app(component, version):
        entry = image_entry(
            board_id, f"{component}-{version}", partition(board_id, component)["offset"]
        )
        return dict(version=version, commit="c" * 40, **entry)

    profile = boards()[board_id]
    return dict(
        name=profile["name"],
        experimental=profile["experimental"],
        layout=profile["layout"],
        flash_size=flash_size(board_id),
        partitions=partitions(board_id),
        images=dict(
            selector=image_entry(board_id, "selector", partition(board_id, "selector")["offset"]),
            bootloader=image_entry(board_id, "bootloader", 0),
            partitions=image_entry(
                board_id, "partitions", 0x8000, 4096, sha(partition_binary(board_id))
            ),
        ),
        apps=dict(
            meshcore=[app("meshcore", version) for version in MESHCORE_VERSIONS],
            meshtastic=[app("meshtastic", "v2.7.26.54e0d8d")],
        ),
    )


def manifest_fixture():
    return dict(
        schema=MANIFEST_SCHEMA,
        version="test",
        chip="ESP32-S3",
        storage_epoch=dict(STORAGE_EPOCH),
        boards={board_id: board_fixture(board_id) for board_id in boards()},
    )


class LayoutTests(unittest.TestCase):
    def test_dependency_locks_match_build_configuration(self):
        import configparser
        import json

        root = Path(__file__).resolve().parents[1]
        lock = json.loads((root / "upstream-lock.json").read_text())
        for component in ("meshcore", "meshtastic"):
            versions = [entry["version"] for entry in lock[component]["versions"]]
            # Every locked version has its own configuration, and nothing else does.
            configured = sorted(p.name for p in (root / component / "versions").iterdir())
            self.assertEqual(configured, sorted(versions))
            self.assertEqual(
                [version_key(v) for v in versions],
                sorted((version_key(v) for v in versions), reverse=True),
                "upstream-lock.json lists versions newest first",
            )
            for version in versions:
                directory = root / component / "versions" / version
                self.assertTrue(list((directory / "patches").glob("*.patch")), directory)
                config = configparser.ConfigParser(interpolation=None)
                config.read(directory / "integration.ini")
                # Board environments are generated by prepare.py and share these settings.
                self.assertEqual([s for s in config.sections() if s.startswith("env:")], [])
                dependencies = config.get("coretastic", "lib_deps").splitlines()
                self.assertEqual(
                    [line.strip() for line in dependencies if line.strip()],
                    json.loads((directory / "dependencies.json").read_text()),
                )

    def test_board_profiles(self):
        self.assertEqual(list(boards()), [V4, V3], "supported boards first, experimental last")
        self.assertFalse(boards()[V4]["experimental"])
        self.assertTrue(boards()[V3]["experimental"])
        for board_id in boards():
            parts = {p["name"]: p for p in partitions(board_id)}
            end = max(p["offset"] + p["size"] for p in parts.values())
            self.assertLessEqual(end, flash_size(board_id))
            # The generated write-guard header carries exactly this board's storage bounds.
            header = layout_header(board_id)
            for constant, name in [("McNvs", "mc_nvs"), ("MtFs", "mt_fs"), ("OtaData", "otadata")]:
                self.assertIn(f"k{constant}Offset = {parts[name]['offset']:#x};", header)
                self.assertIn(f"k{constant}Size = {parts[name]['size']:#x};", header)
            self.assertIn(f"kFlashSize = {flash_size(board_id):#x};", header)
        self.assertNotEqual(partition_binary(V4), partition_binary(V3))

    def test_image_integrity(self):
        data = image_fixture()
        validate_image(data)
        for position in (0, 12, 40, 303, 320):
            broken = bytearray(data)
            broken[position] ^= 1
            with self.assertRaises(ValueError):
                validate_image(broken)
        for cut in (0, 23, 28, 100, 303, 335):
            with self.assertRaises(ValueError):
                validate_image(data[:cut])
        # The header's flash size must match the board.
        validate_image(image_fixture(V3), size=flash_size(V3))
        with self.assertRaisesRegex(ValueError, "8 MiB"):
            validate_image(image_fixture(V4), size=flash_size(V3))

    def test_manifest_rejects_unsafe_changes(self):
        manifest = manifest_fixture()
        validate_manifest(manifest)
        for board_id in boards():
            targets = [("images", name) for name in manifest["boards"][board_id]["images"]]
            targets += [("apps", component, 0) for component in ("meshcore", "meshtastic")]
            for target in targets:
                for key, value in (
                    ("offset", 0x9000),
                    ("size", 0x1000001),
                    ("file", "../x"),
                    ("sha256", "bad"),
                ):
                    broken = copy.deepcopy(manifest)
                    image = broken["boards"][board_id]
                    for part in target:
                        image = image[part]
                    image[key] = value
                    with self.assertRaises(ValueError):
                        validate_manifest(broken)
            broken = copy.deepcopy(manifest)
            broken["boards"][board_id]["partitions"][3]["offset"] = 0x10000
            with self.assertRaises(ValueError):
                validate_manifest(broken)
        # Another board's layout, or a board this flasher does not know, is rejected.
        broken = copy.deepcopy(manifest)
        broken["boards"][V3]["layout"] = boards()[V4]["layout"]
        with self.assertRaisesRegex(ValueError, "layout"):
            validate_manifest(broken)
        broken = copy.deepcopy(manifest)
        broken["boards"]["heltec-v9"] = broken["boards"][V4]
        with self.assertRaisesRegex(ValueError, "Unknown board"):
            validate_manifest(broken)
        broken = copy.deepcopy(manifest)
        broken["boards"] = {}
        with self.assertRaisesRegex(ValueError, "no boards"):
            validate_manifest(broken)
        # A release may ship a subset of the boards this flasher knows.
        subset = copy.deepcopy(manifest)
        del subset["boards"][V3]
        validate_manifest(subset)

    def test_manifest_app_versions(self):
        manifest = manifest_fixture()
        # An app image may not reach into the sector that holds its version record.
        broken = copy.deepcopy(manifest)
        limit = partition(V3, "meshcore")["size"] - SECTOR
        broken["boards"][V3]["apps"]["meshcore"][0]["size"] = limit + 1
        with self.assertRaisesRegex(ValueError, "boundary"):
            validate_manifest(broken)
        for mutate, message in (
            (lambda apps: apps["meshcore"].reverse(), "newest first"),
            (lambda apps: apps["meshcore"].append(apps["meshcore"][0]), "newest first"),
            (lambda apps: apps["meshcore"].clear(), "no versions"),
            (lambda apps: apps.pop("meshtastic"), "unexpected app"),
            (lambda apps: apps["meshcore"][0].update(version="latest"), "unorderable"),
            (lambda apps: apps["meshcore"][0].update(version="../1.2.3"), "invalid version"),
            (lambda apps: apps["meshcore"][0].update(commit="main"), "invalid commit"),
        ):
            broken = copy.deepcopy(manifest)
            mutate(broken["boards"][V4]["apps"])
            with self.assertRaisesRegex(ValueError, message):
                validate_manifest(broken)
        broken = copy.deepcopy(manifest)
        broken["schema"] = 2
        with self.assertRaisesRegex(ValueError, "schema"):
            validate_manifest(broken)

    def test_version_records_and_downgrades(self):
        self.assertEqual(version_key("companion-v1.17.1"), (1, 17, 1))
        self.assertEqual(version_key("v2.7.26.54e0d8d"), (2, 7, 26))
        self.assertIsNone(version_key("latest"))
        self.assertEqual(record_offset(V4, "meshcore"), 0x3FF000)
        self.assertEqual(record_offset(V4, "meshtastic"), 0x9FF000)
        self.assertEqual(record_offset(V3, "meshcore"), 0x25F000)
        self.assertEqual(record_offset(V3, "meshtastic"), 0x55F000)
        record = app_record("meshcore", "companion-v1.17.1", "a" * 64)
        self.assertEqual(len(record), SECTOR)
        self.assertEqual(installed_version(V4, "meshcore", record), "companion-v1.17.1")
        # A record for the other app, or garbage, cannot identify the install.
        self.assertIsNone(installed_version(V4, "meshtastic", record))
        self.assertIsNone(installed_version(V4, "meshcore", b"\0" + record[1:]))
        # v0.1.0 wrote no record and shipped exactly one version of each app, only for the V4.
        blank = b"\xff" * SECTOR
        self.assertEqual(installed_version(V4, "meshcore", blank), "companion-v1.17.0")
        self.assertEqual(installed_version(V4, "meshtastic", blank), "v2.7.26.54e0d8d")
        self.assertIsNone(installed_version(V3, "meshcore", blank))
        self.assertTrue(settings_erase_required("companion-v1.17.1", "companion-v1.16.0"))
        self.assertFalse(settings_erase_required("companion-v1.17.0", "companion-v1.17.1"))
        self.assertFalse(settings_erase_required("companion-v1.17.1", "companion-v1.17.1"))
        self.assertTrue(settings_erase_required(None, "companion-v1.17.1"))

    def test_partition_table_md5(self):
        for board_id in boards():
            table = partition_binary(board_id)
            self.assertEqual(len(table), 4096)
            end = len(partitions(board_id)) * 32
            self.assertEqual(table[end : end + 2], b"\xeb\xeb")
            self.assertEqual(table[end + 16 : end + 32], hashlib.md5(table[:end]).digest())


if __name__ == "__main__":
    unittest.main()
